=== TharindaDilshan/CMS-Joomla/Joomla/media/com_form2content/schemas/f2c_forms_2_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema elementFormDefault="qualified" targetNamespace="http://schemas.form2content.com/forms" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:f2c="http://schemas.form2content.com/forms">


    <element name="forms" type="f2c:formsType"></element>
    
    <complexType name="formsType">
    	<sequence maxOccurs="unbounded" minOccurs="1">
    		<element name="form" type="f2c:formType"></element>
    	</sequence>
    </complexType>

    <complexType name="formType">
    	<sequence maxOccurs="1" minOccurs="1">
    		<element name="id" type="f2c:formidType">
    			<annotation>
    				<documentation>The numeric F2C id for the Article. If the value is zero or blank a new Article will be created.

Also an alternate (external) key may be used.
Make sure the Content Type has a field of type Single Line Textbox that contains a unique value (unique for each Content Type).
Specify the fieldname for this field in the attribute "fieldname" and the alternate key as the value of the id element.
</documentation>
    			</annotation></element>
    		<element name="contenttype">
                <annotation>
                	<documentation>The title of the Content Type</documentation>
                </annotation>
                <simpleType>
    				<restriction base="string">
    					<minLength value="0"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="modified" type="f2c:dateTimeType">
    			<annotation>
    				<documentation>Date in ISO 8601 format when the Article was modified.
Upon import this date will be set to the current date and time of the import.
An empty value is allowed for this field.</documentation>
    			</annotation></element>
    		<element name="ordering" type="int"></element>
    		<element name="attribs" type="f2c:freeFormatXmlType"></element>
    		<element name="metadata" type="f2c:freeFormatXmlType"></element>
    		<element name="fields" type="f2c:fieldsType"></element>    		
    	</sequence>
    </complexType>

	<simpleType name="dateTimeType">
		<union>
			<simpleType>
				<restriction base="string">
				<minLength value="0" />
				<maxLength value="0" />
				</restriction>
			</simpleType>
			<simpleType>
				<restriction base="dateTime" />
			</simpleType>
		</union>
	</simpleType>
	

	<complexType name="freeFormatXmlType">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<any processContents="lax"></any>
		</sequence>
	</complexType>

	<complexType name="tagsType">
		<sequence>
			<element name="tag" type="f2c:tagType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<simpleType name="tagType">
		<restriction base="string">
		</restriction>
	</simpleType>

	<complexType name="fieldsType">
		<sequence>
			<element name="field" type="f2c:fieldType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="fieldType">
		<sequence>
			<element name="fieldname">
				<simpleType>
					<restriction base="string">
						<minLength value="1"></minLength>
					</restriction>
				</simpleType>
			</element>
			<choice>
				<element name="contentBoolean"
					type="f2c:contentBooleanType">
				</element>
				<element name="contentDate"
					type="f2c:contentDateType">
				</element>
				<element name="contentEmail" type="f2c:contentEmailType"></element>
				<element name="contentFileUpload"
					type="f2c:contentFileType">
				</element>
				<element name="contentGeocoder"
					type="f2c:contentGeoType">
				</element>
				<element name="contentHyperlink"
					type="f2c:contentHyperlinkType">
				</element>
				<element name="contentIframe"
					type="f2c:contentIframeType">
				</element>
				<element name="contentImage" type="f2c:contentImageType"></element>
				<element name="contentSingleTextValue"
					type="f2c:contentSingleTextValueType">
				</element>
				<element name="contentMultipleTextValue" type="f2c:contentMultipleTextValueType"></element>
				<element name="contentImageGallery" type="f2c:contentImageGalleryType"></element>
			</choice>

		</sequence>
	</complexType>

	<complexType name="contentBooleanType">
		<sequence>
			<element name="value" type="boolean"></element>
		</sequence>
	</complexType>

	<complexType name="contentDateType">
		<sequence>
			<element name="value" type="f2c:dateTimeType"></element>
		</sequence>
	</complexType>



	<complexType name="stringValuelistType">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="value" type="string" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="contentEmailType">
		<sequence>
			<element name="email" type="string"></element>
			<element name="display_as" type="string"></element>
		</sequence>
	</complexType>



	<simpleType name="includeModeType">
		<restriction base="string">
			<enumeration value="path"></enumeration>
			<enumeration value="url"></enumeration>
			<enumeration value="include"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="fileType">
		<simpleContent>
			<extension base="string">
				<attribute name="includemode" type="f2c:includeModeType" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="contentGeoType">
		<sequence>
			<element name="address" type="string"></element>
			<element name="lat" type="string"></element>
			<element name="lon" type="string"></element>
		</sequence>
	</complexType>


	<complexType name="contentHyperlinkType">
		<sequence>
			<element name="url" type="string"></element>
			<element name="display_as" type="string"></element>
			<element name="title" type="string"></element>
			<element name="target" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="contentIframeType">		
		<sequence>
			<element name="url" type="string"></element>
			<element name="width" type="string"></element>
			<element name="height" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="contentImageType">
		<sequence>
			<element name="filename" type="string"></element>
			<element name="alt" type="string"></element>
			<element name="title" type="string"></element>
			<element name="width" type="string"></element>
			<element name="height" type="string"></element>
			<element name="width_thumbnail" type="string"></element>
			<element name="height_thumbnail" type="string"></element>
            <element name="image" type="f2c:fileType"></element>
            <element name="thumbnail" type="string"></element>
        </sequence>
	</complexType>




	
    


    <complexType name="contentFileType">
    	<sequence>
    		<element name="filename" type="string"></element>
            <element name="file" type="f2c:fileType">
    			</element>
        </sequence>
    </complexType>



    <complexType name="contentSingleTextValueType">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="contentMultipleTextValueType">
    	<sequence>
    		<element name="values" type="f2c:stringValuelistType"></element>
    	</sequence>
    </complexType>

	<complexType name="contentImageGalleryType">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="galleryImage" type="f2c:contentImageGalleryImageType"></element>
		</sequence>
	</complexType>

	<complexType name="contentImageGalleryImageType">
		<sequence>
			<element name="filename" type="string"></element>
			<element name="alt" type="string"></element>
			<element name="title" type="string"></element>
			<element name="width" type="string"></element>
			<element name="height" type="string"></element>
			<element name="width_thumbnail" type="string"></element>
			<element name="height_thumbnail" type="string"></element>
            <element name="image" type="f2c:fileType"></element>
            <element name="thumbnail" type="string"></element>
        </sequence>
	</complexType>

    <complexType name="formidType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="fieldname" type="string"
    				use="optional">
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== TharindaDilshan/CMS-Joomla/Joomla/administrator/components/com_form2content/sample_data/Blog articles_f2c_lite_form1.xml
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schemas.form2content.com/forms" xsi:schemaLocation="http://schemas.form2content.com/forms f2c_forms_2_0_0.xsd">
	<form>
		<id>0</id>
		<contenttype>Blog articles</contenttype>
		<modified>2017-11-11T12:50:56+00:00</modified>
		<ordering>0</ordering>
		<attribs>
			<show_title></show_title>
			<link_titles></link_titles>
			<show_intro>0</show_intro>
			<show_category></show_category>
			<link_category></link_category>
			<show_parent_category></show_parent_category>
			<link_parent_category></link_parent_category>
			<show_author></show_author>
			<link_author></link_author>
			<show_create_date></show_create_date>
			<show_modify_date></show_modify_date>
			<show_publish_date></show_publish_date>
			<show_item_navigation></show_item_navigation>
			<show_icons></show_icons>
			<show_print_icon></show_print_icon>
			<show_email_icon></show_email_icon>
			<show_vote></show_vote>
			<show_hits></show_hits>
			<show_noauth></show_noauth>
			<alternative_readmore></alternative_readmore>
			<article_layout></article_layout>
			<info_block_position>0</info_block_position>
		</attribs>
		<metadata>
			<robots></robots>
			<author></author>
			<rights></rights>
			<xreference></xreference>
		</metadata>
		<fields>
			<field>
				<fieldname>id</fieldname>
				<contentSingleTextValue>
					<value>2</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>title</fieldname>
				<contentSingleTextValue>
					<value>Article templates, the true strength of Form2Content</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>title_alias</fieldname>
				<contentSingleTextValue>
					<value>article-templates-the-true-strength-of-form2content</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>meta_description</fieldname>
				<contentSingleTextValue>
					<value></value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>meta_keywords</fieldname>
				<contentSingleTextValue>
					<value></value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>tags</fieldname>
				<contentMultipleTextValue>
					<values />
				</contentMultipleTextValue>
			</field>
			<field>
				<fieldname>category</fieldname>
				<contentSingleTextValue>
					<value>/x</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>joomla_author</fieldname>
				<contentSingleTextValue>
					<value>joomla</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>author_alias</fieldname>
				<contentSingleTextValue>
					<value></value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>access</fieldname>
				<contentSingleTextValue>
					<value>Public</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>intro_template</fieldname>
				<contentSingleTextValue>
					<value>blog_intro_template.tpl</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>main_template</fieldname>
				<contentSingleTextValue>
					<value>blog_main_template.tpl</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>created</fieldname>
				<contentSingleTextValue>
					<value>2017-11-11T12:50:56+00:00</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>publish_start</fieldname>
				<contentSingleTextValue>
					<value>2017-11-11T12:52:06+00:00</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>publish_stop</fieldname>
				<contentSingleTextValue>
					<value></value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>published</fieldname>
				<contentSingleTextValue>
					<value>unpublished</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>language</fieldname>
				<contentSingleTextValue>
					<value>*</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>featured</fieldname>
				<contentSingleTextValue>
					<value>no</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>intro</fieldname>
				<contentSingleTextValue>
					<value>With a content construction kit there is always a small learning curve. Hopefully our BLOG demo will help you understand the relation between the Form2Contnet submission form (data) and the creation of your Joomla article quickly.</value>
				</contentSingleTextValue>
			</field>
			<field>
				<fieldname>image</fieldname>
				<contentImage>
					<filename>2.png</filename>
					<alt>Open Source Design</alt>
					<title>F2C is developed by Open Source Design</title>
					<width>700</width>
					<height>360</height>
					<width_thumbnail>150</width_thumbnail>
					<height_thumbnail>78</height_thumbnail>
					<image includemode="include"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAArwAAAFoCAYAAAC1/SjnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAUMtJREFUeNrsnQnYXdPVx1eEkJhjipkaYm40oaiQompWWq1q+QxBpVVqnooqqpRWtVGalqoqpaaiVCmlUpqQUjM1xhRTEJHx/fb/2zufV+S99+5zzz7n3Ht/v+dZz0vuOffsu88+5/zP2muv1aurq8sAAAAAANqVuegCAAAAAEDwAgAAAAAgeAEAAAAAELwAAAAAAAheAAAAAAAELwAAAAAAghcAAAAAELwAAAAAAAheAAAAAAAELwAAAABA5Zi70Q3vG9eriu3v62xdZ4PCX9kCwQZyeqHCPOJssrOJzh4KNi7YjCo1dMNBlB8HAIAOEbwV4nPBtgkCF6AVWavbf28x22d3OrvV2TVBGAMAAEAT9Orqasx7U7KHV+LgIGdfcbYEpw06iOedXeXsfGdPldEAPLwAANDqVDmGt3cQuLc5e9jZtxC70IGs4OwwZ086+7P5mQ0AAABoccEroXuAs+ecXW4fn+4F6FS2CaL3MWe70B0AAACtKXi3Dw/zC5wty+kBmCNakHm1szvML9gEAACAFhC8Erc3BFuV0wLQEJs7e8DZJc4WpjsAAACqK3h3CQ/t7TkdAJnY03yc++Z0BQAAQLUEr3LlXmR+apbFaADNoVmSO5yd7awP3QEAAFC+4FXYgry6e3MKAHJFGR3ucjaArgAAAChP8G7o7F4jVhcg9TVGYRYAAIASBO+XzE+79qfrAZKi/L33GGn9AAAAChW8yq17pbO+dDtAIShOXnl7ydkLAAAI3gLYw9lIuhugcLSATQVcqNAGAAAI3oTIu6Q8ob3pboDSRK+yoZC2DAAAELwJUPzg5YhdgNJRKNF1zgbTFQAAgODNj5XNx+ySExSgGqgaG3mvAQAAwZsTfcODlWwMANVihfAiyqwLAAAgeJtklLNBdC9AJVEs75l0AwAAIHizc5D5rAwAUF1UkY10ZQAA0BHMnfP3qXpa1TxHk511caqT8Shd0DDKizuwQu25wNndziZwagAAAMHbOBeFh3oZjHV2vbNx4b/Hc3qhwmhRp8J+lDVBnta1SmjDEkH07srpAACAdqZXV1djzs/7xvWqt8kB4eFZJG86O9/Zhc6e53RCCzMwXEMHlPDSuIOzG3v6cMNBTJAAAACCVygbw5NWXFaGic5OcvYrZ+9xGqGNUOowxdceacWV4X7G2RrOpiJ4AQCgHclr0doxBYrdK8LD+VzELrQhs17m1nN2a0HHVHjFt+h6AABA8PbMsgU9LLX4bLiz3Z29wqmDNucpZ1s7O9bZjAKOd7yVF38PAABQecF7oqWfepXA3cR8CANAJ3FGEL4TEx9HMzSH0d0AAIDg/ThKQ7Z34jY+H8TuOE4XdCi3O9vS0qcPO9KojggAAAjejyGPUJ+E7VNqsaHmF9UAdDJjg+hN6eldwPDyAgAAgvcjaDX5ngnbpgf7tka6MYBZPGQ+Z+7UhMdQWrS+dDUAACB4PRK7KRe5fC084AHgQxTecGDC71cxCkqDAwAAgjeQMjPDOVYjET5Ah3Ox+fR8qTiALgYAAASv2RbmK0OlQF7dYzk1ADWRlzdVuM+GVk6pYwAAgEoJ3pSxuyMsbYwiQDswMVwrqdiTLgYAgE4WvFrQslOi9lzm7G5OC0BD3GjpQn++QvcCAEAnC16FM6TI1alKakdxSgCi0DWTohKbyg2vS/cCAECnCt7tE7XlYvN5dwGgcR5xdk2i796e7gUAAARvfihm9wxOB0AmUl07CF4AAOhIwbtCsLyRh4oCEwDZUBW2FLHvGxtFKAAAoAMF7+aJ2nEhpwKgKS5O8J29nW1K1wIAQKcJ3hQPP8Xt3smpAGgKFaKYnOB7EbwAANBxgndwgjZcb2lWmQN0Eu+ZLzucN4PpWgAA6CTB28fSpCmihDBAda8lBC8AAHSU4F01iN480RTs7ZwGgMoK3gH3jeu1MF0LAACdIngHJjj+Q5Ym7hCgE1Gmk6cSfO/KdC0AACB4s3MfpwCg8tcUghcAADpG8KbIvzuWUwCQK+MSfOeqdCsAAHSK4F02wfEf4RQA5MrjCb5zBboVAAA6RfAOSHB8qqsBVP+aWpZuBQCAThG8ea/UnursFU4BQOUFb3+6FQAAOkXw5v3QQ+wC5M+bln/mEwQvAAB0jODNOwfvRLofIAl5C94F6FIAAOgUwZv3Q4/8uwBpeC/n7+tNlwIAQKcI3rwfelPpfoAk8DIJAACQUfACQGvAyyQAAACCFwAAAAA6hbnpAoA5s+GgrlZt+nqcPQAAgA/BwwsAAAAACF4AAAAAAAQvAAAAAACCFwAAAAAAwQsAAAAAgOAFAAAAAEDwAgAAAACCly4AAAAAAAQvAAAAAACCFwAAAAAAwQsAAAAAgOAFAAAAAEDwAgAAAAAgeAEAAAAAwQsAAAAAgOAFAAAAAGhN5qYLoJMZMXxwjU+HzOkfV3C2urNVgg1w1s/Zks7mcfa6s0nOJjh7wdnTzp509oSzD+hxyJMxY8bQCQAACF6ApunlbKizrZ1t6Ww1Z4tFfsdkZ+Od3ePsFme3OXuVroVmGTJkSKP3+d4NfuWUCv28hZ0t4qyrgWu0K1xTUxgVALywI3gBGkcP2j2d7eVscHioZqWvs1WD7RUezNc5u9jZaLo6KfLAD3I2I6fvm+lsgQaFWF736OfCS1JWjnV2YIPb/sbZ8RU5d/s7OyFC8G7H9QQACF6AxpjP2Tecfct8yEIKlnJ2gLPhzq5xdrqz+xMdaxlnh1p+8frqn8WC8KsnQiaaD+94zdmLzh4zH+YxocDzuZWz37b4mLy9ScHb39myDW57tLO/OLuzAr9boUILR2w/D7cvAEDwAtRnG2c/MO8RLAKJ0C+G457n7DRn7+V8DAmGIyvSv11B7Erc/93Zn52NS3zMGW0wLqc2uf/0iG0V+vAzZxsnGIuxzMwwvgAAenzgAnQ68zo729mNBYrd7szv7BjzXrVP5/zd8rK+UpF+ltd3ySDw5dUe6+wuZ/s5WzDRMd9og/FZtJBbx3woAQAAghegTdCU/7XODqvA9fApZ7c62ztnkdmron2v/t7U2Shn/wq/O++2zmSIZ+KQBC9fAAAIXoCiGTF88OpBYG5ToWbJ03mRVWfhUFEMDL/7JmdrMzpLR7HaPwt/AQAQvAAtKnaVXuwGZ2tVtImnOvt+B54avXwovvdrjNLSUc6zY+kGAEDwArSm2F3R/IKp1SreVMVRHt2Bp0hZBS414kirwFHONqIbAKDVIUsDdJrYVaqjyyy/lGOqrPaW+eISSnqvkATlaVXqsTzSJGlx1zPO/tCBp2uWh/tURm5pKKRBGUQ2C2McAADBC9ACnOVskya/Q9kFtNDtbmdPOXvZPpr+alFnn3C2nrOdnQ2zuHyi3dEsjGIpVZLmvx0qepVp4fwOHrNlLzqcFdpwIrcPAGhVCGmAjmHE8MHb6k8TX6G0ZSovrNXr8jreYb6gwuy5Xt8KoliLsL4QBIPy+76d8bhLODvXqpttITU/cfaZDh66vZvcP49xc5SRtQEAWhg8vNApYldTs2dk3F3VwY6w7GEF8gIf5+x3zn5k2bJC7BDE8zWJu+qDINgbFVJdYftps71Iy8s9qwRvs/Rx9ktnG1r6Ygi/dnalxYWj6IVHuY5TpUB7p8n938qhDcpVfV548ZjGHQUAELwA1WQv8yEGsdzrbE9nT+bQhoedbe/sHPN5TmPRtLK8zFMT9pPStO1rcV7B9+2jXm7t2y8IVcUyyzM41NnW5r3VWVjTvJcx9bT6v53d3GZj/92cvmcD8/mqf8jtBAAQvAAVI3h3s4Qy3BcEap7VuuQFPDSIxNiUTxIcCsu4LmF3aWHS6zl9j1B8s8oHX+BsaWf7OPt2EMKxHGw+TOSZhL+/TxteAnmGwpwYXgj+zZ0FAFoJYnihE1A1r09G7qPY3K9autK0CnG4NMN+e7fwPUHiV1knNC3+pwz7KzziIIZzqchzP9LyyUACAIDgBciR3SO3V1yqQg5SZ0U4NMMxFBqwTIufj6ed7eLs5xn2/br5+GAoD2U5OZxuAAAEL0BFGDF8sPLibh65m+Jkry6gefIex1ZTW8zaI2OBYn4VonB95H4Ki9iKkV0637X4WRMAAAQvQCJWDdYoirE9p8D2Xe7skch9Nm+TcyNPumKrX47cbweGdekQ2gAACF6AChGbO1SZFO4usH1KA3ZV5D7rW/O5WavCeGdnRu6jql99GdqlQ2gDACB4ASrC2pHbKy1X0XlGb7GPF6+ohTzW/dvoHGnx3msR2y/vbHWGdiXQ4su16AYAQPAClMSI4YMXtbhwBjG6hKYqxdOrEdsvadnSelUVpUH7a8T28m4PZIRXAsXI/9TaZ8YBABC8AC2HhOGyEdtPcfafEto5ydnjkfus0Gbn6p+R26/I8K4MKrd9cAXasTCnAgAQvNCJaNo/xhOqEqwvlNTWJyK3X67NzlXswr0BDO8kdGXc72QrP7RhXk4fACB4oRORx2eRiO1VbOKDktr6bOT2i7fZuXoxUmwxhZ4GzXJcn/FaU2hDmdU7uzh9AIDghU5kycgH8ASLWzyWJy9n+G3txPTI7fsxvJMgL+nPnF2bYV+FNnyTLgQABC9AsfSLHOMTSmxrbAnjdst/2ity+ykM72TnYar5KoATM+z/PSNrAwAgeAEKJTaTwcQS2/qexU3JLtFm52rxSNE7g+Gd9EXxOfNxubHMCm0g5AQAELwABRHrNSxT8CoP7dSEv63qrBa5/RsM7+QotOG2DPsptGE43QcACF6AYpjZxuK83dgocvvnGN7JUVy10o29nWHf05x9gi4EAAQvQHrmj9y+zBjeiRa3cKudrt35zHsFG0WhH/9leBfCo5YttGEx86ENvehCAEDwAqQlNpPB1BLb+m6k4F28ja7fnSyucprCGR5heBeGQhvuzrDf9s72p/sAAMELkJbYkIYyvVGxx06V77ToXKZ9nB0duc9YZ28yvAtDCwQV2vB+hn1/4GwVuhAAELwAUCVhWnThgBOdfSpynz8nbM8HDK05Ms7Z9zPsp2qHP6X7AKBs5qYLAKAbSxd4rG85Oy5yH6Vvuz5hm3Z0tmjOzgDNN
